version: "3"
services:
  react:
    build:
      context: ./location-map-app
    volumes:
      - react_build:/app/build
    command: ["true"]

  api:
    build:
      context: ./toeic-api
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  nginx:
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/usr/share/nginx/html

volumes:
  react_build:
