version: "3.8"
services:
  toeic-center-finder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toeic-center-finder-dev
    ports:
      - "80:80"
      - "4000:4000"
    volumes:
      - ./location-map-app/src:/app/frontend/src:ro
      - ./toeic-api:/app/api:rw
    environment:
      - NODE_ENV=development
      - PORT=4000
    restart: unless-stopped