version: "3.8"
services:
  react-build:
    build:
      context: ./location-map-app
      dockerfile: Dockerfile
      args:
        - REACT_APP_GOOGLE_MAPS_API_KEY
    container_name: location-map_react-build
    working_dir: /app
    volumes:
      - react_build:/app/build
    command: sh -c "npm install && npm run build"

  api:
    build:
      context: ./toeic-api
    container_name: location-map_api
    ports:
      - "4000:4000"

  nginx:
    image: nginx:stable-alpine
    container_name: location-map_nginx
    depends_on:
      - react-build
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/usr/share/nginx/html/location-map-app
    restart: unless-stopped

volumes:
  react_build:
